/**
 * Public-domain folk lyric corpus. All songs traditional/pre-1930.
 * Transcribed from Wikisource editions, Hymnary.org, Library of Congress
 * Songs of America, and Lomax Folk Song USA. Deliberately excluded as
 * copyrighted: You Are My Sunshine (1939), This Land Is Your Land (1940),
 * Blowin' in the Wind (1962).
 */
export const SONGS = [
  {
    title: "House of the Rising Sun",
    note: "Traditional American folk, known by 1905. No author.",
    lines: [
      "There is a house in New Orleans",
      "They call it the Rising Sun,",
      "And it has been the ruin of many a poor girl,",
      "And me, oh God, I am one.",
      "If I had only listened to what my mama said,",
      "I would be at home today.",
      "But being so young and foolish, my Lord,",
      "Let a gambler lead me astray.",
      "Now, my mother is a tailor,",
      "She sews those new blue jeans.",
      "And my sweetheart is a drunkard, Lord,",
      "Drinks down in New Orleans.",
      "Now the only thing a drunkard needs",
      "Is a suitcase and a trunk.",
      "And the only time he is satisfied,",
      "Lord, is when he is on the drunk.",
      "Go tell my baby sister",
      "Not to do what I have done.",
      "But shun that house in New Orleans",
      "They call it the Rising Sun.",
      "Well, I am going back to New Orleans;",
      "My race is almost run.",
      "Yes, I am going back to spend my life",
      "Beneath the rising sun.",
    ],
  },
  {
    title: "Scarborough Fair",
    note: "English ballad, 17th-century broadside origin.",
    lines: [
      "Are you going to Scarborough Fair?",
      "Parsley, sage, rosemary and thyme.",
      "Remember me to one who lives there,",
      "She once was a true love of mine.",
      "Tell her to make me a cambric shirt,",
      "Parsley, sage, rosemary and thyme,",
      "Without no seam nor needlework,",
      "Then she will be a true love of mine.",
      "Tell her to find me an acre of land,",
      "Parsley, sage, rosemary and thyme,",
      "Between the salt water and the sea strand,",
      "Then she will be a true love of mine.",
      "Tell her to reap it with a sickle of leather,",
      "Parsley, sage, rosemary and thyme,",
      "And gather it all in a bunch of heather,",
      "Then she will be a true love of mine.",
    ],
  },
  {
    title: "Amazing Grace",
    note: "Words John Newton 1779, tune 1831.",
    lines: [
      "Amazing grace! how sweet the sound,",
      "That saved a wretch like me!",
      "I once was lost, but now am found,",
      "Was blind, but now I see.",
      "It was grace that taught my heart to fear,",
      "And grace my fears relieved;",
      "How precious did that grace appear",
      "The hour I first believed!",
      "Through many dangers, toils and snares,",
      "I have already come;",
      "It is grace that brought me safe thus far,",
      "And grace will lead me home.",
      "When we have been there ten thousand years,",
      "Bright shining as the sun,",
      "We have no less days to sing praise",
      "Than when we first begun.",
    ],
  },
  {
    title: "Oh! Susanna",
    note: "Stephen Foster, published 1848.",
    lines: [
      "I came from Alabama with my banjo on my knee,",
      "I am going to Louisiana, my true love for to see.",
      "It rained all night the day I left, the weather it was dry,",
      "The sun so hot I froze to death, Susanna, do not you cry.",
      "Oh! Susanna, oh! do not you cry for me,",
      "For I have come from Alabama with my banjo on my knee.",
    ],
  },
  {
    title: "Oh My Darling, Clementine",
    note: "American western ballad, credited 1884.",
    lines: [
      "In a cavern, in a canyon, excavating for a mine,",
      "Dwelt a miner, forty-niner, and his daughter Clementine.",
      "Oh my darling, oh my darling, oh my darling Clementine,",
      "You are lost and gone forever, dreadful sorry, Clementine.",
      "Light she was and like a fairy, and her shoes were number nine,",
      "Herring boxes without tops, sandals were for Clementine.",
      "Drove she ducklings to the water, every morning just at nine,",
      "Hit her foot against a splinter, fell into the foaming brine.",
      "Ruby lips above the water, blowing bubbles soft and fine,",
      "Alas for me, I was no swimmer, so I lost my Clementine.",
      "In a churchyard near the canyon, where the myrtle does entwine,",
      "There grow roses and other posies, fertilized by Clementine.",
    ],
  },
  {
    title: "Red River Valley",
    note: "Cowboy standard, earliest manuscript 1879.",
    lines: [
      "From this valley they say you are going,",
      "We will miss your bright eyes and sweet smile,",
      "For they say you are taking the sunshine",
      "That has brightened our pathway awhile.",
      "Come and sit by my side if you love me,",
      "Do not hasten to bid me adieu,",
      "But remember the Red River Valley",
      "And the cowboy who loved you so true.",
      "I have been thinking a long time, my darling,",
      "Of the sweet words you never would say,",
      "Now alas, must my fond hopes all vanish,",
      "For they say you are going away.",
      "Do you think of the valley you are leaving,",
      "Oh how lonely and how dreary it will be?",
      "Do you think of the kind hearts you are breaking,",
      "And the pain you are causing to me?",
    ],
  },
  {
    title: "Down by the Riverside",
    note: "African-American spiritual, slavery-era roots.",
    lines: [
      "Going to lay down my sword and shield",
      "Down by the riverside,",
      "Down by the riverside,",
      "Down by the riverside,",
      "Going to lay down my sword and shield",
      "Down by the riverside,",
      "I am not going to study war no more.",
      "I am not going to study war no more,",
      "I am not going to study war no more.",
      "Going to put on my long white robe",
      "Down by the riverside,",
      "Going to shake hands with all my friends",
      "Down by the riverside,",
    ],
  },
  {
    title: "Take Me Out to the Ball Game",
    note: "Norworth and Von Tilzer, 1908.",
    lines: [
      "Katie Casey was baseball mad, had the fever and had it bad,",
      "Just to root for the hometown crew, every cent Katie blew.",
      "On a Saturday her young beau called to see if she would like to go,",
      "To see a show, but Miss Kate said No, I will tell you what you can do:",
      "Take me out to the ball game, take me out with the crowd,",
      "Buy me some peanuts and Cracker Jack, I do not care if I never get back,",
      "Let me root, root, root for the home team, if they do not win it is a shame,",
      "For it is one, two, three strikes you are out at the old ball game.",
    ],
  },
  {
    title: "Auld Lang Syne",
    note: "Robert Burns 1788, old Scots air.",
    lines: [
      "Should old acquaintance be forgot,",
      "And never brought to mind?",
      "Should old acquaintance be forgot,",
      "And days of long ago?",
      "For days of long ago, my dear,",
      "For days of long ago,",
      "We will take a cup of kindness yet",
      "For days of long ago.",
      "And surely you will buy your pint,",
      "And surely I will buy mine!",
      "And we will take a cup of kindness yet",
      "For days of long ago.",
    ],
  },
  {
    title: "Greensleeves",
    note: "English ballad, registered 1580.",
    lines: [
      "Alas, my love, you do me wrong",
      "To cast me off discourteously,",
      "For I have loved you well and long,",
      "Delighting in your company.",
      "Greensleeves was all my joy,",
      "Greensleeves was my delight,",
      "Greensleeves was my heart of gold,",
      "And who but my lady Greensleeves.",
      "I have been ready at your hand",
      "To grant whatever you would crave,",
      "I have both wagered life and land,",
      "Your love and good-will for to have.",
    ],
  },
  {
    title: "Shenandoah",
    note: "American sea shanty, first print 1876.",
    lines: [
      "Oh Shenandoah, I long to hear you,",
      "Away, you rolling river,",
      "Oh Shenandoah, I long to hear you,",
      "Away, I am bound away across the wide Missouri.",
      "Oh Shenandoah, I love your daughter,",
      "Away, you rolling river,",
      "For her I have crossed the rolling water,",
      "Away, I am bound away across the wide Missouri.",
      "It is seven years since last I have seen you,",
      "Away, you rolling river,",
      "It is seven years since last I have seen you,",
      "Away, I am bound away across the wide Missouri.",
      "Farewell, my dear, I am bound to leave you,",
      "Away, you rolling river,",
      "Oh Shenandoah, I will not deceive you,",
      "Away, I am bound away across the wide Missouri.",
    ],
  },
  {
    title: "Simple Gifts",
    note: "Shaker song, Joseph Brackett 1848.",
    lines: [
      "It is the gift to be simple, it is the gift to be free,",
      "It is the gift to come down where we ought to be,",
      "And when we find ourselves in the place just right,",
      "It will be in the valley of love and delight.",
      "When true simplicity is gained,",
      "To bow and to bend we shall not be ashamed,",
      "To turn, turn will be our delight,",
      "Till by turning, turning we come round right.",
    ],
  },
  {
    title: "Home on the Range",
    note: "Words Higley 1873, Kansas state song.",
    lines: [
      "Oh, give me a home where the buffalo roam,",
      "Where the deer and the antelope play,",
      "Where seldom is heard a discouraging word",
      "And the skies are not cloudy all day.",
      "Home, home on the range,",
      "Where the deer and the antelope play,",
      "Where seldom is heard a discouraging word",
      "And the skies are not cloudy all day.",
      "How often at night when the heavens are bright",
      "With the light from the glittering stars,",
      "Have I stood there amazed and asked as I gazed",
      "If their glory exceeds that of ours.",
    ],
  },
  {
    title: "I Have Been Working on the Railroad",
    note: "American folk medley, first print 1894.",
    lines: [
      "I have been working on the railroad",
      "All the livelong day,",
      "I have been working on the railroad",
      "Just to pass the time away.",
      "Can you not hear the whistle blowing,",
      "Rise up so early in the morn?",
      "Can you not hear the captain shouting,",
      "Dinah, blow your horn?",
      "Dinah, will you not blow,",
      "Dinah, will you not blow,",
      "Dinah, will you not blow your horn?",
      "Someone is in the kitchen with Dinah,",
      "Someone is in the kitchen, I know,",
      "Someone is in the kitchen with Dinah,",
      "Strumming on the old banjo.",
    ],
  },
  {
    title: "Yankee Doodle",
    note: "Anglo-American, sung before the Revolution.",
    lines: [
      "Yankee Doodle went to town",
      "A-riding on a pony,",
      "Stuck a feather in his cap",
      "And called it macaroni.",
      "Yankee Doodle keep it up,",
      "Yankee Doodle dandy,",
      "Mind the music and the step",
      "And with the girls be handy.",
      "Father and I went down to camp",
      "Along with Captain Gooding,",
      "And there we saw the men and boys",
      "As thick as hasty pudding.",
    ],
  },
  {
    title: "When the Saints Go Marching In",
    note: "New Orleans folk origin, first print 1896.",
    lines: [
      "Oh, when the saints go marching in,",
      "Oh, when the saints go marching in,",
      "Oh Lord, I want to be in that number",
      "When the saints go marching in.",
      "Oh, when the drums begin to bang,",
      "Oh, when the stars fall from the sky,",
      "Oh, when the moon turns red with blood,",
    ],
  },
];
